services:
     frontend:
           build: 
              context : .
              dockerfile: Dockerfile
           container_name: edu-spark-con 
           ports: 
              - "3000:80"
           restart: always
           networks:
                - eduspark-network

networks:
  eduspark-network:
    driver: bridge