// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://zggzdxypuoknvundqmmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_qMtw_UzufbNutIlol5HqnA_0gsiwPmJ";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
